using System;
using System.IO;
using System.Text;
using System.Text.Json;

namespace SpaceFindr
{
    public static class D3TreemapHtmlExporter
    {
        public static void ExportD3TreemapToHtml(StorageItem root, string filePath)
        {
            if (root == null) return;
            var sb = new StringBuilder();
            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html><head><meta charset='utf-8'><title>SpaceFindr D3 Treemap</title>");
            sb.AppendLine("<script src='https://cdn.jsdelivr.net/npm/d3@7'></script>");
            sb.AppendLine("<style>body{font-family:sans-serif;} .node text{pointer-events:none;} .tooltip{position:absolute;background:#fff;border:1px solid #ccc;padding:4px 8px;font-size:13px;pointer-events:none;z-index:10;box-shadow:2px 2px 6px #aaa;} .breadcrumb{cursor:pointer;fill:#0074d9;font-size:16px;}</style>");
            sb.AppendLine("</head><body>");
            sb.AppendLine($"<h2>Treemap for {System.Net.WebUtility.HtmlEncode(root.FullPath)}</h2>");
            sb.AppendLine("<div id='treemap'></div>");
            sb.AppendLine("<script>");
            sb.AppendLine($"const data = {GenerateD3Json(root)};");
            sb.AppendLine(@"
const width = 1200, height = 600;
const color = d3.scaleOrdinal().range(['#90ee90','#4682b4','#ffff66','#fbb4ae','#b3cde3','#ccebc5']);
const formatSize = size => {
  const sizes = ['B','KB','MB','GB','TB'];
  let len = size, order = 0;
  while (len >= 1024 && order < sizes.length-1) { order++; len = len/1024; }
  return `${len.toFixed(2)} ${sizes[order]}`;
};

const treemap = data => d3.treemap().size([width, height]).padding(2)
  (d3.hierarchy(data).sum(d => d.size || 0).sort((a, b) => b.value - a.value));

let root = treemap(data);
let currentRoot = root;

const svg = d3.select('#treemap').append('svg')
  .attr('width', width)
  .attr('height', height)
  .style('font', '13px sans-serif');

const group = svg.append('g');

function render(node) {
  group.selectAll('*').remove();
  const nodes = node.children || [];
  group.selectAll('g')
    .data(nodes)
    .join('g')
    .attr('transform', d => `translate(${d.x0},${d.y0})`)
    .each(function(d) {
      d3.select(this).append('rect')
        .attr('width', d => d.x1 - d.x0)
        .attr('height', d => d.y1 - d.y0)
        .attr('fill', d => d.data.isFolder ? '#90ee90' : (d.data.name.endsWith('.exe') ? '#4682b4' : '#ffff66'))
        .attr('stroke', '#222')
        .style('cursor', d => d.children ? 'pointer' : 'default')
        .on('click', (event, d) => {
          if (d.children) {
            currentRoot = d;
            render(d);
          }
        })
        .on('mousemove', function(event, d) {
          tooltip.style('display','block')
            .html(`<b>${d.data.name}</b><br>${d.data.size ? formatSize(d.data.size) : ''}`)
            .style('left', (event.pageX + 10) + 'px')
            .style('top', (event.pageY + 10) + 'px');
        })
        .on('mouseout', function() { tooltip.style('display','none'); });
      d3.select(this).append('text')
        .attr('x', 4)
        .attr('y', 18)
        .text(d.data.name.length > 20 ? d.data.name.substring(0,17) + '...' : d.data.name)
        .attr('fill', '#222');
    });
  // Breadcrumb/back button
  svg.selectAll('.breadcrumb').remove();
  if (node.parent) {
    svg.append('text')
      .attr('class', 'breadcrumb')
      .attr('x', 10)
      .attr('y', 25)
      .text('? Back')
      .on('click', () => {
        currentRoot = node.parent;
        render(node.parent);
      });
  }
}

const tooltip = d3.select('body').append('div').attr('class','tooltip').style('display','none');
render(currentRoot);
");
            sb.AppendLine("</script>");
            sb.AppendLine("<p style='color:#888;font-size:11px'>Generated by SpaceFindr</p>");
            sb.AppendLine("</body></html>");
            Directory.CreateDirectory(System.IO.Path.GetDirectoryName(filePath));
            File.WriteAllText(filePath, sb.ToString());
        }

        private static string GenerateD3Json(StorageItem item)
        {
            var sb = new StringBuilder();
            sb.Append("{");
            sb.Append($"\"name\":\"{EscapeJson(item.Name)}\"");
            if (item.IsFolder && item.Children != null && item.Children.Count > 0)
            {
                sb.Append(",\"isFolder\":true,\"children\":[");
                for (int i = 0; i < item.Children.Count; i++)
                {
                    sb.Append(GenerateD3Json(item.Children[i]));
                    if (i < item.Children.Count - 1) sb.Append(",");
                }
                sb.Append("]");
            }
            else
            {
                sb.Append($",\"isFolder\":false,\"size\":{item.Size}");
            }
            sb.Append("}");
            return sb.ToString();
        }

        private static string EscapeJson(string value)
        {
            if (string.IsNullOrEmpty(value)) return string.Empty;
            return value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\n", "\\n").Replace("\r", "\\r");
        }
    }
}
