using System;
using System.IO;
using System.Text;

namespace SpaceFindr
{
    public static class TreeViewHtmlExporter
    {
        public static void ExportTreeViewToHtml(StorageItem root, string filePath)
        {
            if (root == null) return;
            var sb = new StringBuilder();
            sb.AppendLine("<!DOCTYPE html>");
            sb.AppendLine("<html><head><meta charset='utf-8'><title>SpaceFindr TreeView</title>");
            sb.AppendLine("<link rel='stylesheet' href='https://cdn.jsdelivr.net/npm/jstree@3.3.15/dist/themes/default/style.min.css' />");
            sb.AppendLine("<style>body{font-family:sans-serif;} .jstree-anchor{font-size:14px;}</style>");
            sb.AppendLine("</head><body>");
            sb.AppendLine($"<h2>TreeView for {System.Net.WebUtility.HtmlEncode(root.FullPath)}</h2>");
            sb.AppendLine("<div id='tree'></div>");
            sb.AppendLine("<script src='https://cdn.jsdelivr.net/npm/jquery@3.7.1/dist/jquery.min.js'></script>");
            sb.AppendLine("<script src='https://cdn.jsdelivr.net/npm/jstree@3.3.15/dist/jstree.min.js'></script>");
            sb.AppendLine("<script>");
            sb.AppendLine("$(function() {");
            sb.AppendLine("  $('#tree').jstree({ 'core' : { 'data' : ");
            sb.AppendLine(GenerateJsTreeJson(root));
            sb.AppendLine("  }});");
            sb.AppendLine("});");
            sb.AppendLine("</script>");
            sb.AppendLine("<p style='color:#888;font-size:11px'>Generated by SpaceFindr</p>");
            sb.AppendLine("</body></html>");
            Directory.CreateDirectory(System.IO.Path.GetDirectoryName(filePath));
            System.IO.File.WriteAllText(filePath, sb.ToString());
        }

        private static string GenerateJsTreeJson(StorageItem item)
        {
            var sb = new StringBuilder();
            GenerateJsTreeNode(item, sb, true);
            return sb.ToString();
        }

        private static void GenerateJsTreeNode(StorageItem item, StringBuilder sb, bool isRoot = false)
        {
            sb.Append("[");
            GenerateJsTreeNodeRecursive(item, sb);
            sb.Append("]");
        }

        private static void GenerateJsTreeNodeRecursive(StorageItem item, StringBuilder sb)
        {
            sb.Append("{\"text\":\"");
            sb.Append(JavaScriptStringEncode(item.Name));
            sb.Append($" <span style='color:#888;font-size:11px'>[{FormatSize(item.Size)}]</span>");
            sb.Append("\"");
            if (item.IsFolder && item.Children != null && item.Children.Count > 0)
            {
                sb.Append(",\"icon\":\"jstree-folder\",\"children\":");
                sb.Append("[");
                for (int i = 0; i < item.Children.Count; i++)
                {
                    GenerateJsTreeNodeRecursive(item.Children[i], sb);
                    if (i < item.Children.Count - 1) sb.Append(",");
                }
                sb.Append("]");
            }
            else
            {
                sb.Append(",\"icon\":\"jstree-file\"");
            }
            sb.Append("}");
        }


        // Escapes a string for safe embedding in JavaScript string literals
        private static string JavaScriptStringEncode(string value)
        {
            if (string.IsNullOrEmpty(value)) return string.Empty;
            var sb = new StringBuilder();
            foreach (char c in value)
            {
                switch (c)
                {
                    case '\\': sb.Append("\\\\"); break;
                    case '"': sb.Append("\\\""); break;
                    case '\'': sb.Append("\\'"); break;
                    case '\n': sb.Append("\\n"); break;
                    case '\r': sb.Append("\\r"); break;
                    case '\t': sb.Append("\\t"); break;
                    case '<': sb.Append("\\u003C"); break;
                    case '>': sb.Append("\\u003E"); break;
                    case '&': sb.Append("\\u0026"); break;
                    default:
                        if (c < 32 || c > 126)
                            sb.Append($"\\u{((int)c):x4}");
                        else
                            sb.Append(c);
                        break;
                }
            }
            return sb.ToString();
        }

        private static string FormatSize(long size)
        {
            string[] sizes = { "B", "KB", "MB", "GB", "TB" };
            double len = size;
            int order = 0;
            while (len >= 1024 && order < sizes.Length - 1)
            {
                order++;
                len = len / 1024;
            }
            return $"{len:0.##} {sizes[order]}";
        }
    }
}
